import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import {useState} from 'react';

export default function Home() {
  const [darkMode, setDarkMode ] = useState(false); 
  return (
    <div className={darkMode ? "dark" : "" }>
      <Head>
        <title>Nico Volo Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen"> 
          <nav className="py-10 mb-12 flex justify-between" >
            <h1 className="text-xl font-light font-roboto dark:text-gray-100">nicoVolo</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-gray-100"/></li>
              <li className="text-xl pl-5 underline text-teal-600"><a href="/blog">Blog</a></li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8 font-roboto font-light" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p -10">
            <h2 className="text-5xl py-2 text-teal-600 font-light md:text-6xl dark:text-teal-200">
              Nico Volo
            </h2>
            <h3 className="text-2xl py-2 text-gray-600 md:text-3xl dark:text-gray-200">
              Frontend Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-100">
              Hello there! I'm Nico, a Junior Web Developer in both frontend and backend development, thirsty for learning and passionate about web technologies and building interesting projects. I love learning every day how to create open source projects and contribute to the community.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-200">
            <a className="hover:text-teal-500 dark:hover:text-teal-200" href="#"><AiFillGithub/></a>
            <a className="hover:text-teal-500 dark:hover:text-teal-200" href="#"><AiFillLinkedin/></a>
            <a className="hover:text-teal-500 dark:hover:text-teal-200" href="#"><AiFillInstagram/></a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover"/>
          </div>
        </section>
        <section>
          <div className="md:text-xl max-w-xl mx-auto">
            <h3 className="text-3xl py-2 dark:text-gray-200">Services I offer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-100">I provide SEO optimization, maintenance and creation of modern, fast and mobile friendly websites.
            <br/>
            I worked for 5 years as <span className="text-teal-500 bold dark:text-teal-200">SEO specialist</span> for real estate agency, providing organic traffic and improving Google search positions of the website on the extremely competetive market, as well as speeding up website's speed and usability using latest solutions
            <br/>
            Also, for 2 years I have worked as programming teacher for kids, teaching them how to create awesome games using programming languages like <span className="text-teal-500 bold dark:text-teal-200">JavaScript</span> or <span className="text-teal-500 bold dark:text-teal-200">Python</span>. 
            </p>
          </div>
          <div className="lg:flex gap-10"> 
            <div className="text-center items-center shadow-lg p-10 rounded-xl my-10 dark:shadow-sm dark:shadow-teal-200">
              <Image src={design} width={100} height={100} style={{margin:"auto"}} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-200">Beautiful designs</h3>
              <p className="py-2 dark:text-gray-200">
                Creating beautiful designs suited for your needs following core design theory
              </p>
              <h4 className="py-4 text-teal-400 dark:text-teal-200">Design Tools I use for FrontEnd</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Figma</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Zepplin</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Pixel Perfect</p>
            </div>
            <div className="text-center items-center shadow-lg p-10 rounded-xl my-10 dark:shadow-sm dark:shadow-teal-200">
              <Image src={code} width={100} height={100} style={{margin:"auto"}} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-200">Quality code</h3>
              <p className="py-2 dark:text-gray-200">
                Using the latest technology to best suit the needs
              </p>
              <h4 className="py-4 text-teal-400 dark:text-teal-200">Language and frameworks I use for FrontEnd</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">Javascript</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">React</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Next.js</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Tailwind</p>
            </div>
            <div className="text-center items-center shadow-lg p-10 rounded-xl my-10 dark:shadow-sm dark:shadow-teal-200">
              <Image src={consulting} width={100} height={100} style={{margin:"auto"}} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-200">Search Engine Optimization</h3>
              <p className="py-2 dark:text-gray-200">
              Properly build, structure and tag the website components
              </p>
              <h4 className="py-4 text-teal-400 dark:text-teal-200">Search Engines love when the websites are</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">Lightweighted</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Fast</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Modern</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Adaptative</p>
            </div>
          </div>
        </section>
        <section>
          <div className="md:text-xl max-w-xl mx-auto">
            <h3 className="text-3xl py-1 dark:text-gray-200">Portfolio</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200">I provide SEO optimization, maintenance and creation of modern, fast and mobile friendly websites.
            <br/>
            I worked for 5 years as <span className="text-teal-500 bold dark:text-teal-200">SEO specialist</span> for real estate agency, providing organic traffic and improving Google search positions of the website on the extremely competetive market, as well as speeding up website's speed and usability using latest solutions
            <br/>
            Also, for 2 years I have worked as programming teacher for kids, teaching them how to create awesome games using programming languages like <span className="text-teal-500 bold dark:text-teal-200">JavaScript</span> or <span className="text-teal-500 bold">Python</span>. 
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
        </section>
      </main> 
    </div>
  )
}
